# Generated by Django 4.2.3 on 2023-09-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_rename_email_payment_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='session_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
