# Generated by Django 4.2.2 on 2023-06-25 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DatePlan",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("plan", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VE", "Verified"),
                            ("VG", "Verifying"),
                            ("UV", "Unverified"),
                            ("SH", "Shared"),
                        ],
                        default="UV",
                        max_length=2,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status"], name="dateplan_da_status_8ca4d6_idx"
                    )
                ],
            },
        ),
    ]
