# Generated by Django 4.2.2 on 2023-06-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateplan',
            name='status',
            field=models.CharField(choices=[('VE', 'Verified'), ('VG', 'Verifying'), ('UV', 'Unverified'), ('SH', 'Shared'), ('IN', 'Invalid')], default='UV', max_length=2),
        ),
    ]
