# Generated by Django 4.2.2 on 2023-07-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateplan', '0004_alter_dateplan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateplan',
            name='ai_model',
            field=models.CharField(default='gpt-3.5-turbo', max_length=100),
        ),
        migrations.AddField(
            model_name='dateplan',
            name='prompt',
            field=models.TextField(default=''),
        ),
    ]
