# Generated by Django 4.2.2 on 2023-07-07 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dateplan', '0006_dateplaninfo'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dateplan',
            name='dateplan_da_status_8ca4d6_idx',
        ),
        migrations.RemoveField(
            model_name='dateplaninfo',
            name='plans',
        ),
        migrations.AddField(
            model_name='dateplan',
            name='plan_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dateplan.dateplaninfo'),
        ),
        migrations.AddIndex(
            model_name='dateplan',
            index=models.Index(fields=['status', 'plan_info'], name='dateplan_da_status_851047_idx'),
        ),
    ]
