# Generated by Django 4.2.3 on 2023-07-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateplan', '0007_remove_dateplan_dateplan_da_status_8ca4d6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateplan',
            name='quality',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=100, null=True),
        ),
    ]
