# Generated by Django 4.2.3 on 2023-07-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateplan', '0008_dateplan_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateplaninfo',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
