# Generated by Django 4.2.3 on 2023-07-25 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dateplan", "0009_dateplaninfo_reviewed"),
    ]

    operations = [
        migrations.RemoveField(model_name="dateplan", name="plan",),
        migrations.CreateModel(
            name="DatePlanDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("cityState", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("approximatedCost", models.CharField(max_length=5)),
                ("openDateAndTime", models.CharField(max_length=100)),
                (
                    "googlePlaceId",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "date_plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan",
                        to="dateplan.dateplan",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["place"], name="dateplan_da_place_ddd3b9_idx")
                ],
            },
        ),
    ]
