# Generated by Django 4.2.3 on 2023-07-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dateplan", "0011_remove_dateplandetail_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dateplandetail",
            name="googlePlacePhotoRef",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
