# Generated by Django 4.2.3 on 2023-08-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateplan', '0012_dateplandetail_googleplacephotoref'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dateplan',
            name='dateplan_da_status_851047_idx',
        ),
        migrations.AddField(
            model_name='dateplan',
            name='saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='dateplan',
            index=models.Index(fields=['status', 'plan_info', 'saved'], name='dateplan_da_status_6f75dd_idx'),
        ),
    ]
