# Generated by Django 4.2.3 on 2023-08-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateplan', '0015_dateplandetail_bookinglink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateplandetail',
            name='datePlanEnd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dateplandetail',
            name='datePlanStart',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
