# Generated by Django 4.2.3 on 2023-08-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateplan', '0016_dateplandetail_dateplanend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateplan',
            name='need_babysitter',
            field=models.BooleanField(default=False),
        ),
    ]
