# Generated by Django 4.2.3 on 2023-08-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dateplan', '0017_dateplan_need_babysitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateplandetail',
            name='need_babysitter',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dateplaninfo',
            name='need_babysitter',
            field=models.BooleanField(default=False),
        ),
    ]
