# Generated by Django 4.2.3 on 2023-07-24 23:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid
from ..constants import DEFAULT_PROMPT, DEFAULT_SYSTEM_MSG


def create_default_prompt(apps, schema_editor):
    Prompt = apps.get_model('prompts', 'Prompt')
    PromptMessage = apps.get_model('prompts', 'PromptMessage')

    default_prompt = Prompt.objects.create(
        model='gpt-3.5-turbo',
        max_tokens=1000,
        temperature=0.7,
        ai_service='ChatGPT',
        active=True
    )

    prompt_message_1 = PromptMessage.objects.create(
        prompt=default_prompt,
        order=1,
        role='system',
        content=DEFAULT_SYSTEM_MSG
    )

    prompt_message_2 = PromptMessage.objects.create(
        prompt=default_prompt,
        order=2,
        role='user',
        content=DEFAULT_PROMPT
    )

class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("gpt-3.5-turbo", "GPT-3.5 Turbo"),
                            ("gpt-4", "GPT-4"),
                        ],
                        default="gpt-3.5-turbo",
                        help_text="Model used by the AI service.",
                        max_length=100,
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(
                        default=1000,
                        help_text="Token limits of the response from AI. Maximum 4097.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4097),
                        ],
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.7,
                        help_text="Ranges from 0.0 to 1.0. Lower values for temperature result in more consistent outputs, while higher values generate more diverse and creative results.",
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "ai_service",
                    models.CharField(
                        choices=[
                            ("ChatGPT", "ChatGPT"),
                            ("Llama2", "Llama2"),
                            ("Bard", "Bard"),
                            ("SageMaker", "SageMaker"),
                        ],
                        default="ChatGPT",
                        max_length=100,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PromptMessage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="The order of this message being passed in to the AI service. Must be a positive integer.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("system", "system"),
                            ("user", "user"),
                            ("assistant", "assistant"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The text of the message. e.g. You are a helpful assistant."
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="prompts.prompt",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="prompt",
            index=models.Index(fields=["uuid"], name="prompts_pro_uuid_75e73d_idx"),
        ),
        migrations.AddIndex(
            model_name="promptmessage",
            index=models.Index(fields=["uuid"], name="prompts_pro_uuid_5b3158_idx"),
        ),
        # create default Prompt & PromptMessage objects
        migrations.RunPython(create_default_prompt),
    ]
