# Generated by Django 4.2.3 on 2023-07-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promptmessage",
            name="content",
            field=models.TextField(
                help_text="The text of the message. e.g. You are a helpful assistant. If you are including parameters, please make sure they are wrapped in { } individually."
            ),
        ),
    ]
