# Generated by Django 4.2.4 on 2023-09-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_user_alter_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
