# Generated by Django 4.2.3 on 2023-09-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_user_stripe_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="date_of_bith",
            new_name="date_of_birth",
        ),
    ]
