# Generated by Django 4.2.3 on 2023-10-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_user_google_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_subscribed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="renewal_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
